In [1]:
# Loading in the data
import sklearn
from sklearn.datasets import load_breast_cancer 
# Visualization
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd

# buidling the network
import numpy as np

# Progress Bar
import tqdm as tqdm

import warnings
warnings.filterwarnings('ignore') # supresses warnings

# Loading Dataset,Preprocessing

In [2]:
full_df = pd.read_csv('breast-cancer-wisconsin.csv') # preprocessed data
# full_df.drop(['unname: 0'],inplace=True,axis=1)
full_df.head()

   1000025  5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  1002945  5   4    4    5  7  10  3    2    1    2
1  1015425  3   1    1    1  2   2  3    1    1    2
2  1016277  6   8    8    1  3   4  3    7    1    2
3  1017023  4   1    1    3  2   1  3    1    1    2
4  1017122  8  10   10    8  7  10  9    7    1    4

In [3]:
df = pd.read_csv('breast-cancer-wisconsin.csv')
df.describe()

,1000025,5,1,1.1,1.2,2,3,1.4,1.5,2.1
count,6.980000e+02,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000
mean,1.071807e+06,4.416905,3.137536,3.210602,2.809456,3.217765,3.438395,2.869628,1.590258,2.690544
std,6.175323e+05,2.817673,3.052575,2.972867,2.856606,2.215408,2.440056,3.055004,1.716162,0.951596
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,8.702582e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,1.238354e+06,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [4]:
df.shape

(698, 11)

In [5]:
df.drop('1000025',axis=1,inplace=True)

In [6]:
df.head()

   5   1  1.1  1.2  2 1.3  3  1.4  1.5  2.1
0  5   4    4    5  7  10  3    2    1    2
1  3   1    1    1  2   2  3    1    1    2
2  6   8    8    1  3   4  3    7    1    2
3  4   1    1    3  2   1  3    1    1    2
4  8  10   10    8  7  10  9    7    1    4

In [7]:
df['2.1']=df["2.1"].replace(2,0).replace(4,1)
df.info

,5,1,1.1,1.2,2,3,1.4,1.5,2.1
count,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000,698.000000
mean,4.416905,3.137536,3.210602,2.809456,3.217765,3.438395,2.869628,1.590258,0.345272
std,2.817673,3.052575,2.972867,2.856606,2.215408,2.440056,3.055004,1.716162,0.475798
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,0.000000
50%,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,0.000000
75%,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,1.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000

In [8]:
df['1.3']=df['1.3'].replace('?',0)

df['1.3']=df['1.3'].astype(int)
print(df.dtypes)

5      int64
1      int64
1.1    int64
1.2    int64
2      int64
1.3    int32
3      int64
1.4    int64
1.5    int64
2.1    int64
dtype: object

In [9]:
column_names=list(df.columns)

In [25]:
# df.info()
df.head(10)

   5   1  1.1  1.2  2  1.3  3  1.4  1.5  2.1
0  5   4    4    5  7   10  3    2    1    0
1  3   1    1    1  2    2  3    1    1    0
2  6   8    8    1  3    4  3    7    1    0
3  4   1    1    3  2    1  3    1    1    0
4  8  10   10    8  7   10  9    7    1    1
5  1   1    1    1  2   10  3    1    1    0
6  2   1    2    1  2    1  3    1    1    0
7  2   1    1    1  2    1  1    1    5    0
8  4   2    1    1  2    1  2    1    1    0
9  1   1    1    1  1    1  3    1    1    0

In [11]:
# X : X_train : All the features for training (excluding class)
# Y : Y_train : Actual output (Class)
from sklearn.model_selection import train_test_split

x=df.iloc[:,:]
y=df.iloc[:,-1]
xTrain,xTest,yTrain,yTest=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
# scaling data to 0-1 scaler

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xTrain=scaler.fit_transform(xTrain)
xTest=scaler.fit_transform(xTest)

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
#inititalizing NN
classifier = Sequential()
# units== количество скрытых слоев
#Activation== функция активации.
# input_dims == количество независимых переменных
classifier.add(Dense(units = 5,activation = 'relu', input_dim=10))
classifier.add(Dense(units=3, activation='relu'))
classifier.add(Dense(units=1, activation='sigmoid'))

In [27]:
# setup model for learning
classifier.compile(optimizer="adam",loss='mean_squared_error',metrics=['accuracy'])

In [28]:
# learning process
classifier.fit(xTrain,yTrain,batch_size=10,epochs=100)

Epoch 1/100
56/56 [==============================] - 1s 2ms/step - loss: 0.2121 - accuracy: 0.6075
Epoch 2/100
56/56 [==============================] - 0s 2ms/step - loss: 0.1899 - accuracy: 0.8978
Epoch 3/100
56/56 [==============================] - 0s 2ms/step - loss: 0.1756 - accuracy: 0.9391
Epoch 4/100
56/56 [==============================] - 0s 1ms/step - loss: 0.1625 - accuracy: 0.9552
Epoch 5/100
56/56 [==============================] - 0s 1ms/step - loss: 0.1514 - accuracy: 0.9642
Epoch 6/100
56/56 [==============================] - 0s 2ms/step - loss: 0.1418 - accuracy: 0.9677
Epoch 7/100
56/56 [==============================] - 0s 1ms/step - loss: 0.1330 - accuracy: 0.9731
Epoch 8/100
56/56 [==============================] - 0s 1ms/step - loss: 0.1248 - accuracy: 0.9731
Epoch 9/100
56/56 [==============================] - 0s 1ms/step - loss: 0.1173 - accuracy: 0.9767
Epoch 10/100
56/56 [==============================] - 0s 2ms/step - loss: 0.1102 - accuracy: 0.9767
Epoch 11/100
56/56 [==============================] - 0s 2ms/step - loss: 0.1035 - accuracy: 0.9785
Epoch 12/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0972 - accuracy: 0.9803
Epoch 13/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0913 - accuracy: 0.9803
Epoch 14/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0856 - accuracy: 0.9821
Epoch 15/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0804 - accuracy: 0.9875
Epoch 16/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0752 - accuracy: 0.9892
Epoch 17/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0706 - accuracy: 0.9910
Epoch 18/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0662 - accuracy: 0.9928
Epoch 19/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0621 - accuracy: 0.9928
Epoch 20/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0583 - accuracy: 0.9946
Epoch 21/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0548 - accuracy: 0.9964
Epoch 22/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0516 - accuracy: 0.9964
Epoch 23/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0486 - accuracy: 0.9982
Epoch 24/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0459 - accuracy: 1.0000
Epoch 25/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0433 - accuracy: 1.0000
Epoch 26/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0410 - accuracy: 1.0000
Epoch 27/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0388 - accuracy: 1.0000
Epoch 28/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0367 - accuracy: 1.0000
Epoch 29/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0348 - accuracy: 1.0000
Epoch 30/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0331 - accuracy: 1.0000
Epoch 31/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0314 - accuracy: 1.0000
Epoch 32/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0299 - accuracy: 1.0000
Epoch 33/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0284 - accuracy: 1.0000
Epoch 34/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0271 - accuracy: 1.0000
Epoch 35/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0258 - accuracy: 1.0000
Epoch 36/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0246 - accuracy: 1.0000
Epoch 37/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0235 - accuracy: 1.0000
Epoch 38/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0224 - accuracy: 1.0000
Epoch 39/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0214 - accuracy: 1.0000
Epoch 40/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0205 - accuracy: 1.0000
Epoch 41/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0196 - accuracy: 1.0000
Epoch 42/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0188 - accuracy: 1.0000
Epoch 43/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0180 - accuracy: 1.0000
Epoch 44/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0172 - accuracy: 1.0000
Epoch 45/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0165 - accuracy: 1.0000
Epoch 46/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0158 - accuracy: 1.0000
Epoch 47/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0152 - accuracy: 1.0000
Epoch 48/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0146 - accuracy: 1.0000
Epoch 49/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0140 - accuracy: 1.0000
Epoch 50/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0134 - accuracy: 1.0000
Epoch 51/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0129 - accuracy: 1.0000
Epoch 52/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0124 - accuracy: 1.0000
Epoch 53/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0119 - accuracy: 1.0000
Epoch 54/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0115 - accuracy: 1.0000
Epoch 55/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0110 - accuracy: 1.0000
Epoch 56/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0106 - accuracy: 1.0000
Epoch 57/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0102 - accuracy: 1.0000
Epoch 58/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0099 - accuracy: 1.0000
Epoch 59/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0095 - accuracy: 1.0000
Epoch 60/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0091 - accuracy: 1.0000
Epoch 61/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0088 - accuracy: 1.0000
Epoch 62/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0085 - accuracy: 1.0000
Epoch 63/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0082 - accuracy: 1.0000
Epoch 64/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0079 - accuracy: 1.0000
Epoch 65/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0076 - accuracy: 1.0000
Epoch 66/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0074 - accuracy: 1.0000
Epoch 67/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0071 - accuracy: 1.0000
Epoch 68/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0069 - accuracy: 1.0000
Epoch 69/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0066 - accuracy: 1.0000
Epoch 70/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 71/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0062 - accuracy: 1.0000
Epoch 72/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0060 - accuracy: 1.0000
Epoch 73/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0058 - accuracy: 1.0000
Epoch 74/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 75/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0054 - accuracy: 1.0000
Epoch 76/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0052 - accuracy: 1.0000
Epoch 77/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 78/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 79/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0047 - accuracy: 1.0000
Epoch 80/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 81/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 82/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 83/100

56/56 [==============================] - 0s 1ms/step - loss: 0.0041 - accuracy: 1.0000
Epoch 84/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 85/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 86/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 87/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0036 - accuracy: 1.0000
Epoch 88/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 89/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 90/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 91/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 92/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 93/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 94/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 95/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 96/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 97/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 98/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 99/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 100/100
56/56 [==============================] - 0s 1ms/step - loss: 0.0024 - accuracy: 1.0000

In [29]:
# predicting output
yPred_classifier=classifier.predict(xTest)
yPred=[1 if y>=0.5 else 0 for y in yPred_classifier]
print(yPred)

5/5 [==============================] - 0s 2ms/step
[1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1]

In [30]:
# confusion matrix metric
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yTest,yPred)
print(cm)

[[85  0]
 [ 0 55]]